# Generated by Django 5.2.6 on 2025-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('rate', models.FloatField()),
                ('months', models.PositiveSmallIntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=21)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=21)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=21)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
