# Generated by Django 5.2.6 on 2025-09-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='receiver_hash',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender',
            new_name='sender_hash',
        ),
    ]
